sudo: required
services:
  - docker

before_install:
  - docker build -t bairathi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bairathi/react-test npm test

after_success:
  - docker build -t bairathi/multi-client ./client
  - docker build -t bairathi/multi-nginx ./nginx
  - docker build -t bairathi/multi-server ./server
  - docker build -t bairathi/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bairathi/multi-client
  - docker push bairathi/multi-nginx
  - docker push bairathi/multi-server
  - docker push bairathi/multi-worker